name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Checkout submodules 🌐
        run: git submodule update --init

      - name: Fix git config 👷
        run: |
          echo "https://github.com/$GITHUB_REPOSITORY.git"
          git remote rm origin
          git remote add origin https://github.com/$GITHUB_REPOSITORY.git

      - name: Install and Build 🔧
        run: |
          yarn install
          yarn rollup -c --environment BUILD:kraken

      - name: Deploy FallbackResource 🔀
        run: |
          echo '<html><head><meta http-equiv="refresh" content="0; url=https://krakenh2020.github.io/EduPilotPrototype1/vc4sm-frontend.html"></head><body></body></html>' > dist/index.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
