name: SonarQube Scan
on:
  push:
    branches:
      - master
jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Checkout submodules 🌐
        run: git submodule update --init

      - name: Fix git config 👷
        run: |
          echo "https://github.com/$GITHUB_REPOSITORY.git"
          git remote rm origin
          git remote add origin https://github.com/$GITHUB_REPOSITORY.git
          
      - name: Install and Build 🔧
        run: |
          yarn install
          yarn rollup -c --environment BUILD:kraken

      - name: SonarQube Scan 🚑
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
    
    
    
    
