name: Build and Test
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Checkout submodules
        run: git submodule update --init

      - name: Install  🔧
        run: |
          yarn install
          yarn rollup -c --environment BUILD:kraken

      - name: Lint :shirt:
        run: |
          yarn lint

      - name: Test :rotating_light:
        run: |
          yarn test

      - name: Test Full :rotating_light:
        run: |
          yarn test-full
          
