name: Build and Test
on: push
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      #- name: Install Chrome
      #  run: |
      #    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y chromium-browser
      #    npm i -D puppeteer karma-chrome-launcher
        
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Checkout submodules 🌐
        run: git submodule update --init

      - name: Install  🔧
        run: |
          yarn install
          yarn rollup -c --environment BUILD:kraken

      - name: Lint 🚧
        run: |
          yarn lint

      - name: Test 🚨
        run: |
          yarn test

      - name: Test Full 🔥
        run: |
          yarn test-full
          
